### PR TITLE
Link and url changes

### PR DESCRIPTION
**Pull request by networkException**
- Fixed links to javadoc (from `http://docs.codeoverflow.org/chatoverflow-api` to `https://docs.codeoverflow.org/code/chatoverflow-api`)
 - Changed various urls to https

### CODE REVIEW

**Comment by J0B10** [comment]
https://codeoverflow.org/ is not valid, only the docs are accessible through ssl (as gh pages provides a lets encrypt cert automatically).
Please update your pr.

The rest is fine :smiley::+1:

**Comment by networkException** [comment]
ok sure

**Comment by networkException** [comment]
should I remove it from the examples as well?

**Comment by J0B10** [comment]
Yes, everywhere where `https://codeoverflow.org/` occurs.

**Comment by networkException** [comment]
Ok `https://codeoverflow.org/` should be reverted back to `http://codeoverflow.org/` everywhere

**Pull request merged**
